# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:18:01+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, List, Optional, Union

from pydantic import BaseModel, RootModel


class ApiTokenStatus(BaseModel):
    expiresInMillis: Optional[int] = None
    remainingCalls: Optional[int] = None
    resetsInMillis: Optional[int] = None
    token: Optional[str] = None
    totalRequests: Optional[int] = None
    valid: Optional[bool] = None


class AudioFile(BaseModel):
    attributionText: Optional[str] = None
    attributionUrl: Optional[str] = None
    audioType: Optional[str] = None
    commentCount: Optional[int] = None
    createdAt: Optional[date] = None
    createdBy: Optional[str] = None
    description: Optional[str] = None
    duration: Optional[float] = None
    fileUrl: Optional[str] = None
    id: int
    voteAverage: Optional[float] = None
    voteCount: Optional[int] = None
    voteWeightedAverage: Optional[float] = None
    word: Optional[str] = None


class AudioType(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class AuthenticationToken(BaseModel):
    token: Optional[str] = None
    userId: Optional[int] = None
    userSignature: Optional[str] = None


class Bigram(BaseModel):
    count: Optional[int] = None
    gram1: Optional[str] = None
    gram2: Optional[str] = None
    mi: Optional[float] = None
    wlmi: Optional[float] = None


class Category(BaseModel):
    id: int
    name: Optional[str] = None


class Citation(BaseModel):
    cite: Optional[str] = None
    source: Optional[str] = None


class ContentProvider(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class Citation1(RootModel[Any]):
    root: Any


class ExampleUs(RootModel[Any]):
    root: Any


class Label(RootModel[Any]):
    root: Any


class Note(RootModel[Any]):
    root: Any


class RelatedWord(RootModel[Any]):
    root: Any


class TextPron(RootModel[Any]):
    root: Any


class Definition(BaseModel):
    attributionText: Optional[str] = None
    attributionUrl: Optional[str] = None
    citations: Optional[List[Citation1]] = None
    exampleUses: Optional[List[ExampleUs]] = None
    extendedText: Optional[str] = None
    labels: Optional[List[Label]] = None
    notes: Optional[List[Note]] = None
    partOfSpeech: Optional[str] = None
    relatedWords: Optional[List[RelatedWord]] = None
    score: Optional[float] = None
    seqString: Optional[str] = None
    sequence: Optional[str] = None
    sourceDictionary: Optional[str] = None
    text: Optional[str] = None
    textProns: Optional[List[TextPron]] = None
    word: Optional[str] = None


class Result(RootModel[Any]):
    root: Any


class DefinitionSearchResults(BaseModel):
    results: Optional[List[Result]] = None
    totalResults: Optional[int] = None


class Example1(RootModel[Any]):
    root: Any


class Facet(RootModel[Any]):
    root: Any


class ExampleSearchResults(BaseModel):
    examples: Optional[List[Example1]] = None
    facets: Optional[List[Facet]] = None


class ExampleUsage(BaseModel):
    text: Optional[str] = None


class FacetValue(RootModel[Any]):
    root: Any


class Facet1(BaseModel):
    facetValues: Optional[List[FacetValue]] = None
    name: Optional[str] = None


class FacetValue1(BaseModel):
    count: Optional[int] = None
    value: Optional[str] = None


class Frequency(BaseModel):
    count: Optional[int] = None
    year: Optional[int] = None


class FrequencyItem(RootModel[Any]):
    root: Any


class FrequencySummary(BaseModel):
    frequency: Optional[List[FrequencyItem]] = None
    frequencyString: Optional[str] = None
    totalCount: Optional[int] = None
    unknownYearCount: Optional[int] = None
    word: Optional[str] = None


class Label1(BaseModel):
    text: Optional[str] = None
    type: Optional[str] = None


class Long(BaseModel):
    value: Optional[int] = None


class AppliesToItem(RootModel[str]):
    root: str


class Note1(BaseModel):
    appliesTo: Optional[List[AppliesToItem]] = None
    noteType: Optional[str] = None
    pos: Optional[int] = None
    value: Optional[str] = None


class AllCategory(RootModel[Any]):
    root: Any


class Root(RootModel[Any]):
    root: Any


class StorageAbbrItem(RootModel[str]):
    root: str


class PartOfSpeech(BaseModel):
    allCategories: Optional[List[AllCategory]] = None
    roots: Optional[List[Root]] = None
    storageAbbr: Optional[List[StorageAbbrItem]] = None


class Word(RootModel[str]):
    root: str


class Related(BaseModel):
    gram: Optional[str] = None
    label1: Optional[str] = None
    label2: Optional[str] = None
    label3: Optional[str] = None
    label4: Optional[str] = None
    relationshipType: Optional[str] = None
    words: Optional[List[Word]] = None


class Category1(RootModel[Any]):
    root: Any


class Root1(BaseModel):
    categories: Optional[List[Category1]] = None
    id: int
    name: Optional[str] = None


class ScoredWord(BaseModel):
    baseWordScore: Optional[float] = None
    docTermCount: Optional[int] = None
    id: Optional[int] = None
    lemma: Optional[str] = None
    partOfSpeech: Optional[str] = None
    position: Optional[int] = None
    score: Optional[float] = None
    sentenceId: Optional[int] = None
    stopword: Optional[bool] = None
    word: Optional[str] = None
    wordType: Optional[str] = None


class ScoredWord1(RootModel[Any]):
    root: Any


class Sentence(BaseModel):
    display: Optional[str] = None
    documentMetadataId: Optional[int] = None
    hasScoredWords: Optional[bool] = None
    id: Optional[int] = None
    rating: Optional[int] = None
    scoredWords: Optional[List[ScoredWord1]] = None


class SimpleDefinition(BaseModel):
    note: Optional[str] = None
    partOfSpeech: Optional[str] = None
    source: Optional[str] = None
    text: Optional[str] = None


class SimpleExample(BaseModel):
    id: Optional[int] = None
    text: Optional[str] = None
    title: Optional[str] = None
    url: Optional[str] = None


class StringValue(BaseModel):
    word: Optional[str] = None


class Syllable(BaseModel):
    seq: Optional[int] = None
    text: Optional[str] = None
    type: Optional[str] = None


class TextPron1(BaseModel):
    raw: Optional[str] = None
    rawType: Optional[str] = None
    seq: Optional[int] = None


class User(BaseModel):
    displayName: Optional[str] = None
    email: Optional[str] = None
    faceBookId: Optional[str] = None
    id: Optional[int] = None
    password: Optional[str] = None
    status: Optional[int] = None
    userName: Optional[str] = None
    username: Optional[str] = None


class WordList(BaseModel):
    createdAt: Optional[date] = None
    description: Optional[str] = None
    id: int
    lastActivityAt: Optional[date] = None
    name: Optional[str] = None
    numberWordsInList: Optional[int] = None
    permalink: Optional[str] = None
    type: Optional[str] = None
    updatedAt: Optional[date] = None
    userId: Optional[int] = None
    username: Optional[str] = None


class WordListWord(BaseModel):
    createdAt: Optional[date] = None
    id: int
    numberCommentsOnWord: Optional[int] = None
    numberLists: Optional[int] = None
    userId: Optional[int] = None
    username: Optional[str] = None
    word: Optional[str] = None


class Suggestion(RootModel[str]):
    root: str


class WordObject(BaseModel):
    canonicalForm: Optional[str] = None
    id: int
    originalWord: Optional[str] = None
    suggestions: Optional[List[Suggestion]] = None
    vulgar: Optional[str] = None
    word: Optional[str] = None


class Definition1(RootModel[Any]):
    root: Any


class WordOfTheDay(BaseModel):
    category: Optional[str] = None
    contentProvider: Optional[ContentProvider] = None
    createdAt: Optional[date] = None
    createdBy: Optional[str] = None
    definitions: Optional[List[Definition1]] = None
    examples: Optional[List[Example1]] = None
    htmlExtra: Optional[str] = None
    id: int
    note: Optional[str] = None
    parentId: Optional[str] = None
    publishDate: Optional[date] = None
    word: Optional[str] = None


class WordSearchResult(BaseModel):
    count: Optional[int] = None
    lexicality: Optional[float] = None
    word: Optional[str] = None


class SearchResult(RootModel[Any]):
    root: Any


class WordSearchResults(BaseModel):
    searchResults: Optional[List[SearchResult]] = None
    totalResults: Optional[int] = None


class UseCanonical(Enum):
    false = 'false'
    true = 'true'


class PartOfSpeech1(Enum):
    noun = 'noun'
    adjective = 'adjective'
    verb = 'verb'
    adverb = 'adverb'
    interjection = 'interjection'
    pronoun = 'pronoun'
    preposition = 'preposition'
    abbreviation = 'abbreviation'
    affix = 'affix'
    article = 'article'
    auxiliary_verb = 'auxiliary-verb'
    conjunction = 'conjunction'
    definite_article = 'definite-article'
    family_name = 'family-name'
    given_name = 'given-name'
    idiom = 'idiom'
    imperative = 'imperative'
    noun_plural = 'noun-plural'
    noun_posessive = 'noun-posessive'
    past_participle = 'past-participle'
    phrasal_prefix = 'phrasal-prefix'
    proper_noun = 'proper-noun'
    proper_noun_plural = 'proper-noun-plural'
    proper_noun_posessive = 'proper-noun-posessive'
    suffix = 'suffix'
    verb_intransitive = 'verb-intransitive'
    verb_transitive = 'verb-transitive'


class SourceDictionaries(Enum):
    all = 'all'
    ahd_5 = 'ahd-5'
    century = 'century'
    wiktionary = 'wiktionary'
    webster = 'webster'
    wordnet = 'wordnet'


class IncludeTags(Enum):
    false = 'false'
    true = 'true'


class SourceDictionaries1(RootModel[Union[List[str], SourceDictionaries]]):
    root: Union[List[str], SourceDictionaries]


class IncludeDuplicates(Enum):
    false = 'false'
    true = 'true'


class SourceDictionary(Enum):
    ahd_5 = 'ahd-5'
    century = 'century'
    wiktionary = 'wiktionary'
    webster = 'webster'
    wordnet = 'wordnet'


class SourceDictionary2(Enum):
    ahd_5 = 'ahd-5'
    century = 'century'
    cmu = 'cmu'
    macmillan = 'macmillan'
    wiktionary = 'wiktionary'
    webster = 'webster'
    wordnet = 'wordnet'


class TypeFormat(Enum):
    ahd_5 = 'ahd-5'
    arpabet = 'arpabet'
    gcide_diacritical = 'gcide-diacritical'
    IPA = 'IPA'


class RelationshipTypes(Enum):
    synonym = 'synonym'
    antonym = 'antonym'
    variant = 'variant'
    equivalent = 'equivalent'
    cross_reference = 'cross-reference'
    related_word = 'related-word'
    rhyme = 'rhyme'
    form = 'form'
    etymologically_related_term = 'etymologically-related-term'
    hypernym = 'hypernym'
    hyponym = 'hyponym'
    inflected_form = 'inflected-form'
    primary = 'primary'
    same_context = 'same-context'
    verb_form = 'verb-form'
    verb_stem = 'verb-stem'
    has_topic = 'has_topic'


class SortBy(Enum):
    alpha = 'alpha'
    count = 'count'


class SortOrder(Enum):
    asc = 'asc'
    desc = 'desc'


class IncludeSourceDictionaries(Enum):
    ahd_5 = 'ahd-5'
    century = 'century'
    cmu = 'cmu'
    macmillan = 'macmillan'
    wiktionary = 'wiktionary'
    webster = 'webster'
    wordnet = 'wordnet'


class ExcludeSourceDictionaries(Enum):
    ahd_5 = 'ahd-5'
    century = 'century'
    cmu = 'cmu'
    macmillan = 'macmillan'
    wiktionary = 'wiktionary'
    webster = 'webster'
    wordnet = 'wordnet'


class Example(BaseModel):
    documentId: Optional[int] = None
    exampleId: Optional[int] = None
    id: Optional[int] = None
    provider: Optional[ContentProvider] = None
    rating: Optional[float] = None
    score: Optional[ScoredWord] = None
    sentence: Optional[Sentence] = None
    text: Optional[str] = None
    title: Optional[str] = None
    url: Optional[str] = None
    word: Optional[str] = None
    year: Optional[int] = None
