# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:18:01+00:00

from __future__ import annotations

from typing import List

from pydantic import RootModel

from . import WordObject


class JsonRandomWordsGetResponse(RootModel[List[WordObject]]):
    root: List[WordObject]
