# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:18:01+00:00

from __future__ import annotations

from typing import List

from pydantic import RootModel

from . import AudioFile, Bigram, Definition, Related, Syllable, TextPron1


class JsonWordAudioGetResponse(RootModel[List[AudioFile]]):
    root: List[AudioFile]


class JsonWordDefinitionsGetResponse(RootModel[List[Definition]]):
    root: List[Definition]


class JsonWordEtymologiesGetResponse(RootModel[List[str]]):
    root: List[str]


class JsonWordHyphenationGetResponse(RootModel[List[Syllable]]):
    root: List[Syllable]


class JsonWordPhrasesGetResponse(RootModel[List[Bigram]]):
    root: List[Bigram]


class JsonWordPronunciationsGetResponse(RootModel[List[TextPron1]]):
    root: List[TextPron1]


class JsonWordRelatedWordsGetResponse(RootModel[List[Related]]):
    root: List[Related]
