# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:18:01+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity
from fastapi import Query

from models import (
    DefinitionSearchResults,
    Example,
    ExampleSearchResults,
    ExcludeSourceDictionaries,
    FrequencySummary,
    IncludeDuplicates,
    IncludeSourceDictionaries,
    IncludeTags,
    PartOfSpeech1,
    RelationshipTypes,
    SortBy,
    SortOrder,
    SourceDictionaries1,
    SourceDictionary,
    SourceDictionary2,
    TypeFormat,
    UseCanonical,
    WordObject,
    WordOfTheDay,
    WordSearchResults,
)
from models.Word import (
    JsonWordAudioGetResponse,
    JsonWordDefinitionsGetResponse,
    JsonWordEtymologiesGetResponse,
    JsonWordHyphenationGetResponse,
    JsonWordPhrasesGetResponse,
    JsonWordPronunciationsGetResponse,
    JsonWordRelatedWordsGetResponse,
)
from models.Words import JsonRandomWordsGetResponse

app = MCPProxy(
    description='Wordnik is the worlds biggest online English dictionary, by number of words',
    title='Wordnik',
    version='4.0',
    servers=[{'url': 'https://api.wordnik.com/v4'}],
)


@app.get(
    '/word.json/{word}/audio',
    description=""" The metadata includes a time-expiring fileUrl which allows reading the audio file directly from the API.  Currently only audio pronunciations from the American Heritage Dictionary in mp3 format are supported. """,
    tags=['word_metadata_retrieval'],
    security=[],
)
def get_audio(
    word: str,
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
    limit: Optional[int] = 50,
):
    """
    Fetches audio metadata for a word.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/word.json/{word}/definitions',
    tags=['word_metadata_retrieval', 'dictionary_lookup_functions'],
    security=[],
)
def get_definitions(
    word: str,
    limit: Optional[int] = 200,
    part_of_speech: Optional[PartOfSpeech1] = Query(None, alias='partOfSpeech'),
    include_related: Optional[str] = Query('false', alias='includeRelated'),
    source_dictionaries: Optional[SourceDictionaries1] = Query(
        None, alias='sourceDictionaries'
    ),
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
    include_tags: Optional[IncludeTags] = Query('false', alias='includeTags'),
):
    """
    Return definitions for a word
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/word.json/{word}/etymologies', tags=['word_metadata_retrieval'], security=[])
def get_etymologies(
    word: str,
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
):
    """
    Fetches etymology data
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/word.json/{word}/examples', tags=['word_examples_and_phrases'], security=[])
def get_examples(
    word: str,
    include_duplicates: Optional[IncludeDuplicates] = Query(
        'false', alias='includeDuplicates'
    ),
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
    skip: Optional[int] = 0,
    limit: Optional[int] = 5,
):
    """
    Returns examples for a word
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/word.json/{word}/frequency', tags=['word_usage_statistics'], security=[])
def get_word_frequency(
    word: str,
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
    start_year: Optional[int] = Query(1800, alias='startYear'),
    end_year: Optional[int] = Query(2012, alias='endYear'),
):
    """
    Returns word usage over time
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/word.json/{word}/hyphenation', tags=['word_metadata_retrieval'], security=[])
def get_hyphenation(
    word: str,
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
    source_dictionary: Optional[SourceDictionary] = Query(
        None, alias='sourceDictionary'
    ),
    limit: Optional[int] = 50,
):
    """
    Returns syllable information for a word
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/word.json/{word}/phrases', tags=['word_examples_and_phrases'], security=[])
def get_phrases(
    word: str,
    limit: Optional[int] = 5,
    wlmi: Optional[int] = 0,
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
):
    """
    Fetches bi-gram phrases for a word
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/word.json/{word}/pronunciations', tags=['word_metadata_retrieval'], security=[]
)
def get_text_pronunciations(
    word: str,
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
    source_dictionary: Optional[SourceDictionary2] = Query(
        None, alias='sourceDictionary'
    ),
    type_format: Optional[TypeFormat] = Query(None, alias='typeFormat'),
    limit: Optional[int] = 50,
):
    """
    Returns text pronunciations for a given word
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/word.json/{word}/relatedWords',
    tags=['word_relationship_exploration'],
    security=[],
)
def get_related_words(
    word: str,
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
    relationship_types: Optional[RelationshipTypes] = Query(
        None, alias='relationshipTypes'
    ),
    limit_per_relationship_type: Optional[int] = Query(
        10, alias='limitPerRelationshipType'
    ),
):
    """
    Given a word as a string, returns relationships from the Word Graph
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/word.json/{word}/scrabbleScore', tags=['word_usage_statistics'], security=[])
def get_scrabble_score(word: str):
    """
    Returns the Scrabble score for a word
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/word.json/{word}/topExample', tags=['word_examples_and_phrases'], security=[]
)
def get_top_example(
    word: str,
    use_canonical: Optional[UseCanonical] = Query('false', alias='useCanonical'),
):
    """
    Returns a top example for a word
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/words.json/randomWord',
    tags=['random_word_generation', 'dictionary_lookup_functions'],
    security=[],
)
def get_random_word(
    has_dictionary_def: Optional[str] = Query('true', alias='hasDictionaryDef'),
    include_part_of_speech: Optional[str] = Query(None, alias='includePartOfSpeech'),
    exclude_part_of_speech: Optional[str] = Query(None, alias='excludePartOfSpeech'),
    min_corpus_count: Optional[int] = Query(0, alias='minCorpusCount'),
    max_corpus_count: Optional[int] = Query(-1, alias='maxCorpusCount'),
    min_dictionary_count: Optional[int] = Query(1, alias='minDictionaryCount'),
    max_dictionary_count: Optional[int] = Query(-1, alias='maxDictionaryCount'),
    min_length: Optional[int] = Query(5, alias='minLength'),
    max_length: Optional[int] = Query(-1, alias='maxLength'),
):
    """
    Returns a single random WordObject
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/words.json/randomWords', tags=['random_word_generation'], security=[])
def get_random_words(
    has_dictionary_def: Optional[str] = Query('true', alias='hasDictionaryDef'),
    include_part_of_speech: Optional[str] = Query(None, alias='includePartOfSpeech'),
    exclude_part_of_speech: Optional[str] = Query(None, alias='excludePartOfSpeech'),
    min_corpus_count: Optional[int] = Query(0, alias='minCorpusCount'),
    max_corpus_count: Optional[int] = Query(-1, alias='maxCorpusCount'),
    min_dictionary_count: Optional[int] = Query(1, alias='minDictionaryCount'),
    max_dictionary_count: Optional[int] = Query(-1, alias='maxDictionaryCount'),
    min_length: Optional[int] = Query(5, alias='minLength'),
    max_length: Optional[int] = Query(-1, alias='maxLength'),
    sort_by: Optional[SortBy] = Query(None, alias='sortBy'),
    sort_order: Optional[SortOrder] = Query(None, alias='sortOrder'),
    limit: Optional[int] = 10,
):
    """
    Returns an array of random WordObjects
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/words.json/reverseDictionary',
    tags=['dictionary_lookup_functions', 'word_relationship_exploration'],
    security=[],
)
def reverse_dictionary(
    query: str,
    find_sense_for_word: Optional[str] = Query(None, alias='findSenseForWord'),
    include_source_dictionaries: Optional[IncludeSourceDictionaries] = Query(
        None, alias='includeSourceDictionaries'
    ),
    exclude_source_dictionaries: Optional[ExcludeSourceDictionaries] = Query(
        None, alias='excludeSourceDictionaries'
    ),
    include_part_of_speech: Optional[str] = Query(None, alias='includePartOfSpeech'),
    exclude_part_of_speech: Optional[str] = Query(None, alias='excludePartOfSpeech'),
    min_corpus_count: Optional[int] = Query(5, alias='minCorpusCount'),
    max_corpus_count: Optional[int] = Query(-1, alias='maxCorpusCount'),
    min_length: Optional[int] = Query(1, alias='minLength'),
    max_length: Optional[int] = Query(-1, alias='maxLength'),
    expand_terms: Optional[str] = Query(None, alias='expandTerms'),
    include_tags: Optional[IncludeTags] = Query('false', alias='includeTags'),
    sort_by: Optional[SortBy] = Query(None, alias='sortBy'),
    sort_order: Optional[SortOrder] = Query(None, alias='sortOrder'),
    skip: Optional[str] = '0',
    limit: Optional[int] = 10,
):
    """
    Reverse dictionary search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/words.json/search/{query}',
    tags=[
        'dictionary_lookup_functions',
        'word_metadata_retrieval',
        'word_usage_statistics',
    ],
    security=[],
)
def search_words(
    allow_regex: Optional[str] = Query('false', alias='allowRegex'),
    query: str = ...,
    case_sensitive: Optional[str] = Query('true', alias='caseSensitive'),
    include_part_of_speech: Optional[str] = Query(None, alias='includePartOfSpeech'),
    exclude_part_of_speech: Optional[str] = Query(None, alias='excludePartOfSpeech'),
    min_corpus_count: Optional[int] = Query(5, alias='minCorpusCount'),
    max_corpus_count: Optional[int] = Query(-1, alias='maxCorpusCount'),
    min_dictionary_count: Optional[int] = Query(1, alias='minDictionaryCount'),
    max_dictionary_count: Optional[int] = Query(-1, alias='maxDictionaryCount'),
    min_length: Optional[int] = Query(1, alias='minLength'),
    max_length: Optional[int] = Query(-1, alias='maxLength'),
    skip: Optional[int] = 0,
    limit: Optional[int] = 10,
):
    """
    Searches words
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/words.json/wordOfTheDay', tags=['word_of_the_day_fetching'], security=[])
def get_word_of_the_day(date: Optional[str] = None):
    """
    Returns a specific WordOfTheDay
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
